export const CHECK = "CHECK";
export const CHECK_SUCCESS = "CHECK_SUCCESS";
export const CHECK_FAILURE = "CHECK_FAILURE";

export const LOCAL_REGISTER = "LOCAL_REGISTER";
export const LOCAL_REGISTER_SUCCESS = "LOCAL_REGISTER_SUCCESS";
export const LOCAL_REGISTER_FAILURE = "LOCAL_REGISTER_FAILURE";
